server:
  port: 18080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect